# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 577)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Mitra Mono")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QGroupBox {\n"
"    border: 1px solid black;\n"
"    border-radius: 8px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"    background-color: #ffe5a0;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* position at the top center*/\n"
"    padding: 0 3px;\n"
"}\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border: 1px solid #b0b0b0;\n"
"    border-radius: 8px;\n"
"    background: #ffe5a0;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"QTabBar::tab {\n"
"    border: 1px solid #404040;\n"
"    background: #ffe090;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"QFrame {\n"
"    background-color: #ffe5a0;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #b0b0b0;\n"
"}\n"
"QLineEdit{\n"
"    border: 2px solid #b0b0b0;\n"
"    border-radius: 8px;\n"
"    background-color:#fff5c0;\n"
"}\n"
"QTextEdit {\n"
"    border: 2px solid #b0b0b0;\n"
"    border-radius: 8px;\n"
"}\n"
"QLabel {\n"
"    border: 0px solid #b0b0b0;\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    min-width: 80px;\n"
"    border-radius: 8px;\n"
"    background-color: #D0D0D0;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #F0D0D0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 500))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 235, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 143, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 235, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 235, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 143, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 235, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 235, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 143, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 229, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 215, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame.setPalette(palette)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_setup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 400))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_pw = QtWidgets.QLineEdit(self.groupBox_7)
        self.line_pw.setMinimumSize(QtCore.QSize(50, 0))
        self.line_pw.setMaximumSize(QtCore.QSize(200, 30))
        self.line_pw.setText("")
        self.line_pw.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_pw.setObjectName("line_pw")
        self.gridLayout_2.addWidget(self.line_pw, 2, 0, 1, 1)
        self.label_selection = QtWidgets.QLabel(self.groupBox_7)
        self.label_selection.setMaximumSize(QtCore.QSize(600, 90))
        self.label_selection.setWordWrap(True)
        self.label_selection.setObjectName("label_selection")
        self.gridLayout_2.addWidget(self.label_selection, 3, 1, 1, 1)
        self.Buttongetfile = QtWidgets.QPushButton(self.groupBox_7)
        self.Buttongetfile.setMaximumSize(QtCore.QSize(150, 30))
        self.Buttongetfile.setObjectName("Buttongetfile")
        self.gridLayout_2.addWidget(self.Buttongetfile, 2, 1, 1, 1)
        self.ButtonBoxSetup = QtWidgets.QDialogButtonBox(self.groupBox_7)
        self.ButtonBoxSetup.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ButtonBoxSetup.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ButtonBoxSetup.setObjectName("ButtonBoxSetup")
        self.gridLayout_2.addWidget(self.ButtonBoxSetup, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_3.setMinimumSize(QtCore.QSize(60, 100))
        self.groupBox_3.setMaximumSize(QtCore.QSize(150, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radio_Sec = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_Sec.setGeometry(QtCore.QRect(70, 20, 96, 23))
        self.radio_Sec.setChecked(True)
        self.radio_Sec.setObjectName("radio_Sec")
        self.radio_Min = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_Min.setGeometry(QtCore.QRect(70, 40, 96, 23))
        self.radio_Min.setObjectName("radio_Min")
        self.radio_Hour = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_Hour.setGeometry(QtCore.QRect(70, 60, 96, 23))
        self.radio_Hour.setObjectName("radio_Hour")
        self.lineEdit_Rtime = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Rtime.setGeometry(QtCore.QRect(5, 40, 61, 30))
        self.lineEdit_Rtime.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEdit_Rtime.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_Rtime.setToolTip("")
        self.lineEdit_Rtime.setToolTipDuration(3)
        self.lineEdit_Rtime.setObjectName("lineEdit_Rtime")
        self.gridLayout_2.addWidget(self.groupBox_3, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 1, 0, 1, 2)
        self.Buttonmakecsv = QtWidgets.QPushButton(self.groupBox)
        self.Buttonmakecsv.setMinimumSize(QtCore.QSize(84, 0))
        self.Buttonmakecsv.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Buttonmakecsv.setObjectName("Buttonmakecsv")
        self.gridLayout.addWidget(self.Buttonmakecsv, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_user = QtWidgets.QLabel(self.frame_2)
        self.label_user.setMinimumSize(QtCore.QSize(200, 0))
        self.label_user.setMaximumSize(QtCore.QSize(200, 30))
        self.label_user.setObjectName("label_user")
        self.horizontalLayout.addWidget(self.label_user)
        self.label_version = QtWidgets.QLabel(self.frame_2)
        self.label_version.setMinimumSize(QtCore.QSize(150, 0))
        self.label_version.setMaximumSize(QtCore.QSize(150, 30))
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout.addWidget(self.label_version)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_setup, "")
        self.tab_2_run = QtWidgets.QWidget()
        self.tab_2_run.setObjectName("tab_2_run")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2_run)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2_run)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_status = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status.setFont(font)
        self.lineEdit_status.setFrame(True)
        self.lineEdit_status.setReadOnly(True)
        self.lineEdit_status.setObjectName("lineEdit_status")
        self.verticalLayout_9.addWidget(self.lineEdit_status)
        self.textEdit_results = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_results.setFont(font)
        self.textEdit_results.setReadOnly(True)
        self.textEdit_results.setObjectName("textEdit_results")
        self.verticalLayout_9.addWidget(self.textEdit_results)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lcdNumbercountdown = QtWidgets.QLCDNumber(self.groupBox_8)
        self.lcdNumbercountdown.setMaximumSize(QtCore.QSize(200, 40))
        self.lcdNumbercountdown.setObjectName("lcdNumbercountdown")
        self.horizontalLayout_4.addWidget(self.lcdNumbercountdown)
        self.line = QtWidgets.QFrame(self.groupBox_8)
        self.line.setMinimumSize(QtCore.QSize(20, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.Button_Stop = QtWidgets.QPushButton(self.groupBox_8)
        self.Button_Stop.setMaximumSize(QtCore.QSize(50, 30))
        self.Button_Stop.setObjectName("Button_Stop")
        self.horizontalLayout_4.addWidget(self.Button_Stop)
        self.Button_Run = QtWidgets.QPushButton(self.groupBox_8)
        self.Button_Run.setMaximumSize(QtCore.QSize(50, 30))
        self.Button_Run.setObjectName("Button_Run")
        self.horizontalLayout_4.addWidget(self.Button_Run)
        self.checkBox_sound = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_sound.setMinimumSize(QtCore.QSize(60, 30))
        self.checkBox_sound.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkBox_sound.setToolTip("")
        self.checkBox_sound.setToolTipDuration(-1)
        self.checkBox_sound.setWhatsThis("")
        self.checkBox_sound.setObjectName("checkBox_sound")
        self.horizontalLayout_4.addWidget(self.checkBox_sound)
        self.verticalLayout_9.addWidget(self.groupBox_8)
        self.textEdit_results1 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.textEdit_results1.setObjectName("textEdit_results1")
        self.verticalLayout_9.addWidget(self.textEdit_results1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2_run, "")
        self.tab_3_zipup = QtWidgets.QWidget()
        self.tab_3_zipup.setObjectName("tab_3_zipup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3_zipup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3_zipup)
        self.groupBox_4.setMinimumSize(QtCore.QSize(400, 200))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setMaximumSize(QtCore.QSize(500, 80))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_enter_filename = QtWidgets.QLineEdit(self.groupBox_5)
        self.line_enter_filename.setMaximumSize(QtCore.QSize(200, 30))
        self.line_enter_filename.setText("")
        self.line_enter_filename.setMaxLength(30)
        self.line_enter_filename.setObjectName("line_enter_filename")
        self.horizontalLayout_2.addWidget(self.line_enter_filename)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setMaximumSize(QtCore.QSize(250, 40))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setMaximumSize(QtCore.QSize(500, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_ZipPassword = QtWidgets.QLineEdit(self.groupBox_6)
        self.line_ZipPassword.setMaximumSize(QtCore.QSize(200, 30))
        self.line_ZipPassword.setText("")
        self.line_ZipPassword.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_ZipPassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_ZipPassword.setObjectName("line_ZipPassword")
        self.horizontalLayout_3.addWidget(self.line_ZipPassword)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setMaximumSize(QtCore.QSize(150, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.Button_zip = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_zip.setMaximumSize(QtCore.QSize(80, 30))
        self.Button_zip.setObjectName("Button_zip")
        self.verticalLayout_7.addWidget(self.Button_zip)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_3_zipup, "")
        self.tab_4_help = QtWidgets.QWidget()
        self.tab_4_help.setObjectName("tab_4_help")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4_help)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textEdit_help = QtWidgets.QTextEdit(self.tab_4_help)
        self.textEdit_help.setReadOnly(True)
        self.textEdit_help.setObjectName("textEdit_help")
        self.verticalLayout_6.addWidget(self.textEdit_help)
        self.tabWidget.addTab(self.tab_4_help, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_4.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.ButtonBoxSetup.rejected.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SNMP monitor"))
        self.groupBox.setTitle(_translate("MainWindow", "Select Zipfile"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Details"))
        self.line_pw.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_selection.setText(_translate("MainWindow", "Selected Filename"))
        self.Buttongetfile.setText(_translate("MainWindow", "Select the Zip File"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Repeat"))
        self.radio_Sec.setText(_translate("MainWindow", "Seconds"))
        self.radio_Min.setText(_translate("MainWindow", "Minutes"))
        self.radio_Hour.setText(_translate("MainWindow", "Hours"))
        self.Buttonmakecsv.setText(_translate("MainWindow", "Make a new empty CSV file"))
        self.label_user.setText(_translate("MainWindow", "Username"))
        self.label_version.setText(_translate("MainWindow", "Version"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _translate("MainWindow", "Setup"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Activity"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Activate"))
        self.Button_Stop.setText(_translate("MainWindow", "Stop"))
        self.Button_Run.setText(_translate("MainWindow", "Run"))
        self.checkBox_sound.setText(_translate("MainWindow", "Play Sounds"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2_run), _translate("MainWindow", "Run"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Zip a File"))
        self.label_3.setText(_translate("MainWindow", "Enter a filename to create. Using the data within unitdetails.csv, the file will be created"))
        self.label.setText(_translate("MainWindow", "Enter the name of the file you want to create (inc. the .zip)"))
        self.label_2.setText(_translate("MainWindow", "Enter the new Password"))
        self.Button_zip.setText(_translate("MainWindow", "ZIP now"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3_zipup), _translate("MainWindow", "Create Zip"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4_help), _translate("MainWindow", "Help"))
